# Generated by Django 4.1.1 on 2022-09-13 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_profile_pic',
            new_name='profile_pic',
        ),
    ]
