# Generated by Django 4.1.1 on 2022-09-20 03:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app', '0006_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessin_year',
            name='created_att',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessin_year',
            name='updated_att',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
