# Generated by Django 4.1.1 on 2022-11-04 20:20

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app', '0014_student_leav'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('sessin_year_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Auth_app.sessin_year')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Auth_app.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Attendence_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('attendance_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Auth_app.attendence')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, to='Auth_app.student')),
            ],
        ),
    ]
